-- -------------------------------------------------
-- Solving all queries related to music store database for analysis
-- -------------------------------------------------

use music_store_db;


-- 1. Find the top 3 employees with the highest total revenue from their customers
select
	e.employee_id,
    e.last_name,
    e.first_name,
    sum(i.total) as total_revenue
from employee e
join customer c
	on e.employee_id = c.support_rep_id
join invoice i 
	on c.customer_id = i.customer_id
group by e.employee_id
order by total_revenue desc
limit 3;



-- 2. Get the average revenue per track in each genre, considering all invoice lines where the track was purchased
WITH track_revenue AS (
    SELECT 
        t.track_id,
        t.genre_id,
        SUM(il.quantity * il.unit_price) AS track_revenue
    FROM track t
    JOIN invoice_line il 
		ON t.track_id = il.track_id
    GROUP BY t.track_id, t.genre_id
)
SELECT 
    g.name AS genre_name,
    AVG(tr.track_revenue) AS avg_revenue_per_track
FROM genre g
JOIN track_revenue tr 
	ON g.genre_id = tr.genre_id
GROUP BY g.genre_id
ORDER BY avg_revenue_per_track DESC;




-- 3. List the top 3 most purchased tracks in each genre
with cte_1 as (
	select 
		il.track_id, 
		sum(il.quantity) as total_track_sale,
		t.name as track_name,
		g.name as genre_name
	from invoice_line il
	join track t
		on il.track_id = t.track_id
	join genre g
		on t.genre_id = g.genre_id
	group by il.track_id
),
cte_2 as (
	select 
		genre_name,
		track_name,
		total_track_sale,
		dense_rank() over(partition by genre_name order by total_track_sale desc) as rankings
	from cte_1
) select * from cte_2
where rankings <= 3;




-- 4. Find the revenue generated by playlists, grouped by the employee who manages them 
with cte_3 as (
select 
	e.employee_id, 
    e.last_name,
    e.first_name,
    i.customer_id, 
    i.invoice_id, 
    il.invoice_line_id, 
    il.track_id, 
    pt.playlist_id,
    il.unit_price, 
    il.quantity 
from invoice i
join invoice_line il
	on i.invoice_id = il.invoice_id
join customer c
	on c.customer_id = i.customer_id
join employee e
	on c.support_rep_id = e.employee_id
join playlist_track pt
	on il.track_id = pt.track_id 
) select pl.name, first_name, last_name, sum(quantity * unit_price) as revenue_by_playlist
from cte_3
join playlist pl
	on cte_3.playlist_id = pl.playlist_id
group by pl.name, employee_id
order by revenue_by_playlist desc;




-- 5. Find the customer who have purchased the highest number of different tracks
select
	c.customer_id,
    c.first_name,
    c.last_name,
    count(il.track_id)
from customer c
join invoice i
	on c.customer_id = i.customer_id
join invoice_line il
	on il.invoice_id = i.invoice_id
group by c.customer_id
order by c.customer_id desc
limit 1; 



-- 6. Retrieve the average number of tracks per playlist and the total revenue generated by each playlist
with cte_4 as (
	select
		pl.name as playlist_name,
		t.track_id as track_id,
		sum(il.quantity * il.unit_price) as total_revenue
	from playlist pl
	join playlist_track pltrack
		on pl.playlist_id = pltrack.playlist_id
	join track t
		on pltrack.track_id = t.track_id
	join invoice_line il
		on il.track_id = t.track_id
	group by t.track_id, pl.name
), cte_5 as ( 
select 
	playlist_name,
    count(track_id) as count_of_tracks,
    sum(total_revenue) as total_pl_revenue
from cte_4
group by playlist_name
) select
	playlist_name,
    avg(count_of_tracks) over() as avg_track_per_playlist,
    total_pl_revenue
from cte_5
;



-- 7. Get the total revenue generated by each employee from their customers, split by album and track
with cte_6 as (
	select 
		il.invoice_id,
		il.track_id,
		t.name as track_name,
		a.album_id,
		a.title as album_name,
		(il.quantity * il.unit_price) as revenue
	from invoice_line il
	join track t
		on il.track_id = t.track_id
	join album a
		on t.album_id = a.album_id
	order by invoice_id
) select 
	e.employee_id,
    album_name,
    track_name,
    sum(revenue)
from cte_6
join invoice i
	on cte_6.invoice_id = i.invoice_id
join customer c 
	on c.customer_id = i.customer_id
join employee e 
	on e.employee_id = c.support_rep_id
group by e.employee_id, album_name, track_name
order by e.employee_id, album_name, track_name;















